# Generated by Django 3.0.2 on 2020-02-29 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200229_1424'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
