# Generated by Django 3.0.2 on 2020-03-01 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_movie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomeServices',
            new_name='HomeService',
        ),
    ]
