# Generated by Django 3.0.2 on 2020-03-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200301_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeservice',
            name='short_name',
            field=models.CharField(default=' ', max_length=10),
            preserve_default=False,
        ),
    ]
