# Generated by Django 3.0.2 on 2020-03-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_homeservice_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeservice',
            name='slug_name',
            field=models.CharField(default='view', max_length=10),
            preserve_default=False,
        ),
    ]
