# Generated by Django 3.0.2 on 2020-03-01 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_homeservice_slug_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
