# Generated by Django 3.0.2 on 2020-03-01 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200301_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='released',
        ),
    ]
