# Generated by Django 3.0.2 on 2020-04-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_movie_released'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeservice',
            name='materialize_icon',
            field=models.CharField(default='home', max_length=30),
            preserve_default=False,
        ),
    ]
