# Generated by Django 3.0.2 on 2020-04-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_homeservice_materialize_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='search_string',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
