# Generated by Django 3.0.2 on 2020-06-19 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_movie_search_string'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieCsvData',
            fields=[
                ('header_title', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('key_in_movie', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
