# Generated by Django 3.0.2 on 2020-06-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_moviecsvdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviecsvdata',
            name='header_title',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
