# Generated by Django 3.0.2 on 2020-06-20 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200620_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviecsvdata',
            old_name='key_in_movie',
            new_name='key_in_table',
        ),
    ]
