# Generated by Django 3.0.2 on 2020-06-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20200620_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoGame',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('combined_ranking', models.FloatField(null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('summary', models.TextField(null=True)),
                ('image', models.TextField(null=True)),
                ('trailer_url', models.TextField(null=True)),
                ('combined_ranking_order', models.PositiveIntegerField(null=True)),
                ('released_order', models.PositiveIntegerField(null=True)),
                ('release_year', models.PositiveIntegerField(null=True)),
                ('release_month', models.CharField(max_length=9, null=True)),
                ('release_day', models.PositiveIntegerField(null=True)),
                ('min_completion_time', models.FloatField(null=True)),
                ('players', models.CharField(max_length=30, null=True)),
                ('rating', models.CharField(max_length=4, null=True)),
                ('genres', models.CharField(max_length=150, null=True)),
                ('publishers', models.CharField(max_length=100, null=True)),
                ('developers', models.CharField(max_length=100, null=True)),
                ('search_string', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoGameCsvData',
            fields=[
                ('header_title', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('key_in_table', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
