# Generated by Django 3.0.2 on 2020-07-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20200705_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaDataBases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_description', models.TextField(null=True)),
                ('materialize_icon', models.CharField(max_length=30)),
                ('card_name', models.CharField(max_length=10)),
                ('source_image', models.CharField(max_length=30)),
                ('slug_name', models.CharField(max_length=10)),
                ('link_description', models.CharField(max_length=30)),
            ],
        ),
    ]
