# Generated by Django 3.0.2 on 2020-07-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_mediadatabases'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediadatabases',
            name='fa_icon',
            field=models.CharField(default='_', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediadatabases',
            name='page_title',
            field=models.CharField(default='_', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediadatabases',
            name='template_folder',
            field=models.CharField(default='_', max_length=10),
            preserve_default=False,
        ),
    ]
