# Generated by Django 3.0.2 on 2020-07-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20200711_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardGame',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('thumbnail', models.TextField(null=True)),
                ('image', models.TextField(null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('summary', models.TextField(null=True)),
                ('release_year', models.PositiveIntegerField(null=True)),
                ('min_players', models.PositiveIntegerField(null=True)),
                ('max_players', models.PositiveIntegerField(null=True)),
                ('best_players', models.PositiveIntegerField(null=True)),
                ('language_dependence', models.CharField(max_length=100, null=True)),
                ('difficulty', models.FloatField(null=True)),
                ('combined_ranking_order', models.PositiveIntegerField(null=True)),
                ('released_order', models.PositiveIntegerField(null=True)),
                ('search_string', models.CharField(max_length=100, null=True)),
                ('runtime', models.FloatField(null=True)),
            ],
        ),
    ]
