# Generated by Django 3.0.2 on 2020-07-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_boardgame_min_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='combined_ranking',
            field=models.FloatField(null=True),
        ),
    ]
