# Generated by Django 3.0.2 on 2020-07-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_boardgame_combined_ranking'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardGameCsvData',
            fields=[
                ('header_title', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('key_in_table', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
