# Generated by Django 3.0.2 on 2020-07-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_boardgamecsvdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='release_year',
            field=models.IntegerField(null=True),
        ),
    ]
