# Generated by Django 3.0.2 on 2020-07-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20200712_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediadatabases',
            name='image_max_width',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
    ]
