# Generated by Django 3.0.2 on 2020-07-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_mediadatabases_image_max_width'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120, null=True)),
                ('status', models.CharField(max_length=10, null=True)),
                ('image_url', models.TextField(null=True)),
                ('type', models.CharField(max_length=10, null=True)),
                ('volumes', models.PositiveIntegerField(null=True)),
                ('summary', models.TextField(null=True)),
                ('background', models.TextField(null=True)),
                ('authors', models.CharField(max_length=30, null=True)),
                ('serializations', models.CharField(max_length=40, null=True)),
                ('combined_ranking', models.FloatField(null=True)),
                ('runtime', models.FloatField(null=True)),
                ('combined_ranking_order', models.PositiveIntegerField(null=True)),
                ('released_order', models.PositiveIntegerField(null=True)),
                ('publish_from_day', models.PositiveIntegerField(null=True)),
                ('publish_from_month', models.CharField(max_length=3, null=True)),
                ('publish_from_year', models.PositiveIntegerField(null=True)),
                ('publish_last_day', models.PositiveIntegerField(null=True)),
                ('publish_last_month', models.CharField(max_length=3, null=True)),
                ('publish_last_year', models.PositiveIntegerField(null=True)),
                ('genres_short', models.CharField(max_length=60, null=True)),
                ('genres_long', models.CharField(max_length=120, null=True)),
                ('search_string', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MangaCsvData',
            fields=[
                ('header_title', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('key_in_table', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
