# Generated by Django 3.0.2 on 2020-07-25 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_manga_mangacsvdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manga',
            old_name='publish_from_day',
            new_name='release_day',
        ),
        migrations.RenameField(
            model_name='manga',
            old_name='publish_from_month',
            new_name='release_month',
        ),
        migrations.RenameField(
            model_name='manga',
            old_name='publish_from_year',
            new_name='release_year',
        ),
    ]
