# Generated by Django 3.0.2 on 2020-08-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20200725_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('thumbnail', models.TextField(null=True)),
                ('url_trailer', models.TextField(null=True)),
                ('title', models.CharField(max_length=120, null=True)),
                ('type', models.CharField(max_length=10, null=True)),
                ('source', models.CharField(max_length=20, null=True)),
                ('episode_count', models.PositiveIntegerField(null=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('rating', models.CharField(max_length=30, null=True)),
                ('combined_ranking', models.FloatField(null=True)),
                ('summary', models.TextField(null=True)),
                ('background', models.TextField(null=True)),
                ('runtime', models.PositiveIntegerField(null=True)),
                ('combined_ranking_order', models.PositiveIntegerField(null=True)),
                ('search_string', models.CharField(max_length=60, null=True)),
                ('released_order', models.PositiveIntegerField(null=True)),
                ('release_day', models.PositiveIntegerField(null=True)),
                ('release_month', models.CharField(max_length=3, null=True)),
                ('release_year', models.PositiveIntegerField(null=True)),
                ('aired_to_day', models.CharField(max_length=2, null=True)),
                ('aired_to_month', models.CharField(max_length=3, null=True)),
                ('aired_to_year', models.CharField(max_length=4, null=True)),
                ('genres_short', models.CharField(max_length=70, null=True)),
                ('genres_long', models.CharField(max_length=100, null=True)),
                ('licensors', models.CharField(max_length=40, null=True)),
                ('producers', models.CharField(max_length=40, null=True)),
                ('studios', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnimeCsvData',
            fields=[
                ('header_title', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('key_in_table', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
