# Generated by Django 3.0.2 on 2020-08-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_anime_animecsvdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediadatabases',
            name='default_id',
            field=models.CharField(default='NULL', max_length=30),
            preserve_default=False,
        ),
    ]
