# Generated by Django 3.0.2 on 2020-08-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_mediadatabases_default_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediadatabases',
            name='button_max_width',
            field=models.PositiveIntegerField(default=180),
            preserve_default=False,
        ),
    ]
